version: '3.8'
services:
  go-admin-api:
    container_name: go-admin
    image: go-admin:latest
    privileged: true
    restart: always
    ports:
      - 7000:8000
    volumes:
      - ./config/:/go-admin-api/config/
      - ./static/:/static/
      - ./temp/:/go-admin-api/temp/
    networks:
      - myweb
networks:
  myweb:
    driver: bridge

